### Overview
Making a prediction using a linear regression model is a common use case in ML. In this guide tutorial, we build the model that predicts if a driver will complete a trip based on a number of features ingested into Feast.

The basic local mode gives you ability to quickly try Feast, while the advanced mode shows how you can use Feast in a production setting, in particular for the Google Cloud Platform (GCP) cloud.

This tutorial uses Feast with scikit learn to:

* Train a model locally using data from BigQuery
* Test the model for online inference using SQLite (for fast iteration)
* Test the model for online inference using Firestore (to represent production)

## Step 1: Install feast, scikit-learn

Install feast, gcp dependencies and scikit-learn

In [1]:
!pip install feast scikit-learn 'feast[gcp]'

Collecting feast
  Downloading feast-0.64.0-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: click<9.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (8.4.2)
Collecting colorama<1,>=0.3.9 (from feast)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: dill~=0.3.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.3.8)
Requirement already satisfied: protobuf>=4.24.0 in /usr/local/lib/python3.12/dist-packages (from feast) (5.29.6)
Requirement already satisfied: Jinja2<4,>=2 in /usr/local/lib/python3.12/dist-packages (from feast) (3.1.6)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from feast) (4.26.0)
Requirement already satisfied: mmh3 in /usr/local/lib/python3.12/dist-packages (from feast) (5.2.1)
Requirement already satisfied: numpy<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (2.0.2)
Requirement already satisfied: pandas<3,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from feast) (2.2.2)
Collecting pyarrow>=21.0.0 (from feast)
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: pydantic>=2.10.6 in /usr/local/lib/python3.12/dist-packages (from feast) (2.13.4)
Requirement already satisfied: pygments<3,>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from feast) (2.20.0)
Requirement already satisfied: PyYAML<7,>=5.4.0 in /usr/local/lib/python3.12/dist-packages (from feast) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from feast) (2.32.4)
Requirement already satisfied: SQLAlchemy>1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy[mypy]>1->feast) (2.0.51)
Requirement already satisfied: tabulate<1,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.9.0)
Collecting tenacity<9,>=7 (from feast)
  Downloading tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: toml<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.10.2)
Requirement already satisfied: tqdm<5,>=4 in /usr/local/lib/python3.12/dist-packages (from feast) (4.67.3)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from feast) (4.5.2)
Requirement already satisfied: fastapi>=0.68.0 in /usr/local/lib/python3.12/dist-packages (from feast) (0.138.0)
Requirement already satisfied: starlette>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from feast) (1.3.1)
Collecting uvicorn<=0.34.0,>=0.30.6 (from uvicorn[standard]<=0.34.0,>=0.30.6->feast)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Collecting uvicorn-worker (from feast)
  Downloading uvicorn_worker-0.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting gunicorn (from feast)
  Downloading gunicorn-26.0.0-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: dask>=2024.2.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]>=2024.2.1->feast) (2026.6.0)
Collecting prometheus_client<0.25.0,>=0.20.0 (from feast)
  Downloading prometheus_client-0.24.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from feast) (5.9.5)
Collecting bigtree>=0.19.2 (from feast)
  Downloading bigtree-1.5.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from feast) (2.13.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: google-api-core<3,>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from feast[gcp]) (2.30.3)
Requirement already satisfied: googleapis-common-protos<2,>=1.52.0 in /usr/local/lib/python3.12/dist-packages (from feast[gcp]) (1.75.0)
Requirement already satisfied: google-cloud-bigquery<4,>=2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (3.42.1)
Requirement already satisfied: google-cloud-bigquery-storage<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from feast[gcp]) (2.39.0)
Requirement already satisfied: google-cloud-datastore<3,>=2.16.0 in /usr/local/lib/python3.12/dist-packages (from feast[gcp]) (2.25.0)
Collecting google-cloud-storage<3,>=1.34.0 (from feast[gcp])
  Downloading google_cloud_storage-2.19.0-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting google-cloud-bigtable<3,>=2.11.0 (from feast[gcp])
  Downloading google_cloud_bigtable-2.40.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: fsspec>=2024.1.0 in /usr/local/lib/python3.12/dist-packages (from feast[gcp]) (2025.3.0)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (3.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (26.2)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (0.12.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.68.0->feast) (0.0.4)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3,>=1.23.0->feast[gcp]) (1.28.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3,>=1.23.0->feast[gcp]) (2.49.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (2.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (2.9.0.post0)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery-storage<3,>=2.0.0->feast[gcp]) (1.81.1)
Requirement already satisfied: pandas-gbq>=0.26.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (0.30.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.7.0)
Collecting protobuf>=4.24.0 (from feast)
  Downloading protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigtable<3,>=2.11.0->feast[gcp]) (0.14.4)
Requirement already satisfied: google-crc32c<2.0.0dev,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigtable<3,>=2.11.0->feast[gcp]) (1.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2<4,>=2->feast) (3.0.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.3->feast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.3->feast) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10.6->feast) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.10.6->feast) (2.46.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->feast) (2026.6.17)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy>1->SQLAlchemy[mypy]>1->feast) (3.5.2)
Collecting mypy>=0.910 (from SQLAlchemy[mypy]>1->feast)
  Downloading mypy-2.1.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=1.0.1->feast) (4.14.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<=0.34.0,>=0.30.6->uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.16.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.8.0)
Requirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (1.2.2)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.22.1)
Requirement already satisfied: watchfiles>=0.13 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (1.2.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (15.0.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->feast) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->feast) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->feast) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->feast) (2026.5.1)
INFO: pip is looking at multiple versions of uvicorn-worker to determine which version is compatible with other requirements. This could take a while.
Collecting uvicorn-worker (from feast)
  Downloading uvicorn_worker-0.3.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (49.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (4.9.1)
Requirement already satisfied: pyopenssl>=20.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (26.3.0)
Collecting mypy_extensions>=1.0.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pathspec>=1.0.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Collecting librt>=0.11.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading librt-0.12.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.3 kB)
Collecting ast-serialize<1.0.0,>=0.3.0 (from mypy>=0.910->SQLAlchemy[mypy]>1->feast)
  Downloading ast_serialize-0.6.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (75.2.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.9.1)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.4.0)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.17.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (2.0.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (2.0.0)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp])
  Downloading grpcio_status-1.82.0-py3-none-any.whl.metadata (1.2 kB)
Collecting grpcio<2.0.0,>=1.59.0 (from google-cloud-bigquery-storage<3,>=2.0.0->feast[gcp])
  Downloading grpcio-1.82.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (0.6.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (3.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (3.3.1)
Downloading feast-0.64.0-py3-none-any.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 48.6 MB/s eta 0:00:00
Downloading bigtree-1.5.1-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.7/131.7 kB 5.2 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading google_cloud_bigtable-2.40.0-py3-none-any.whl (567 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 567.2/567.2 kB 16.0 MB/s eta 0:00:00
Downloading google_cloud_storage-2.19.0-py2.py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 6.2 MB/s eta 0:00:00
Downloading prometheus_client-0.24.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 3.2 MB/s eta 0:00:00
Downloading protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl (327 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 327.1/327.1 kB 14.1 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 17.4 MB/s eta 0:00:00
Downloading tenacity-8.5.0-py3-none-any.whl (28 kB)
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 2.9 MB/s eta 0:00:00
Downloading gunicorn-26.0.0-py3-none-any.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 9.0 MB/s eta 0:00:00
Downloading uvicorn_worker-0.3.0-py3-none-any.whl (5.3 kB)
Downloading mypy-2.1.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 54.3 MB/s eta 0:00:00
Downloading ast_serialize-0.6.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 32.3 MB/s eta 0:00:00
Downloading grpcio_status-1.82.0-py3-none-any.whl (14 kB)
Downloading grpcio-1.82.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 109.7 MB/s eta 0:00:00
Downloading librt-0.12.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (518 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 518.4/518.4 kB 34.7 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pathspec-1.1.1-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.3 MB/s eta 0:00:00
Installing collected packages: uvicorn, tenacity, pyarrow, protobuf, prometheus_client, pathspec, mypy_extensions, librt, gunicorn, grpcio, colorama, bigtree, ast-serialize, uvicorn-worker, mypy, grpcio-status, feast, google-cloud-storage, google-cloud-bigtable
  Attempting uninstall: uvicorn
    Found existing installation: uvicorn 0.49.0
    Uninstalling uvicorn-0.49.0:
      Successfully uninstalled uvicorn-0.49.0
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: prometheus_client
    Found existing installation: prometheus_client 0.25.0
    Uninstalling prometheus_client-0.25.0:
      Successfully uninstalled prometheus_client-0.25.0
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.81.1
    Uninstalling grpcio-1.81.1:
      Successfully uninstalled grpcio-1.81.1
  Attempting uninstall: grpcio-status
    Found existing installation: grpcio-status 1.71.2
    Uninstalling grpcio-status-1.71.2:
      Successfully uninstalled grpcio-status-1.71.2
  Attempting uninstall: google-cloud-storage
    Found existing installation: google-cloud-storage 3.12.0
    Uninstalling google-cloud-storage-3.12.0:
      Successfully uninstalled google-cloud-storage-3.12.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

#### Check feast version

In [10]:
!feast version

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Feast SDK Version: "0.64.0"

In [3]:
! feast init iris-feature-store-creation-sqlite

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'

Creating a new Feast repository in /content/iris-feature-store-creation-sqlite.

In [4]:
!pwd

/content

In [8]:
import pandas as pd

df = pd.read_csv("/content/iris_data_adapted_for_feast.csv")

df["sepal_area"] = df["sepal_length"] * df["sepal_width"]
df["petal_area"] = df["petal_length"] * df["petal_width"]
df["sepal_ratio"] = df["sepal_length"] / df["sepal_width"]
df["petal_ratio"] = df["petal_length"] / df["petal_width"]
df["flower_area"] = df["sepal_area"] + df["petal_area"]
df["petal_to_sepal_ratio"] = df["petal_area"] / df["sepal_area"]

df["event_timestamp"] = pd.to_datetime(
    df["event_timestamp"],
    utc=True
)

df["created_timestamp"] = pd.to_datetime(
    df["created_timestamp"],
    utc=True
)

df.to_parquet("/content//iris-feature-store-creation-sqlite/feature_repo/data/iris.parquet", index=False)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [10]:
%cd /content/iris-feature-store-creation-sqlite/feature_repo
!feast apply

/content/iris-feature-store-creation-sqlite/feature_repo
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/usr/local/lib/python3.12/dist-packages/xarray/core/dtypes.py:111: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  NAT_TYPES = {np.datetime64("NaT").dtype, np.timedelta64("NaT").dtype}
/content/iris-feature-store-creation-sqlite/feature_repo/feature_definitions.py:19: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'iris'.
  iris = Entity(
Applying changes for project iris_feature_store_creation_sqlite
No changes to registry
No changes to infrastructure

In [12]:
!pwd

/content

In [11]:
%cd /content

/content

In [24]:
!zip -r iris-feature-store-creation-sqlite.zip iris-feature-store-creation-sqlite

  adding: iris-feature-store-creation-sqlite/ (stored 0%)
  adding: iris-feature-store-creation-sqlite/__init__.py (stored 0%)
  adding: iris-feature-store-creation-sqlite/.gitignore (deflated 35%)
  adding: iris-feature-store-creation-sqlite/feature_repo/ (stored 0%)
  adding: iris-feature-store-creation-sqlite/feature_repo/feature_definitions.py (deflated 77%)
  adding: iris-feature-store-creation-sqlite/feature_repo/__init__.py (stored 0%)
  adding: iris-feature-store-creation-sqlite/feature_repo/__pycache__/ (stored 0%)
  adding: iris-feature-store-creation-sqlite/feature_repo/__pycache__/test_workflow.cpython-312.pyc (deflated 48%)
  adding: iris-feature-store-creation-sqlite/feature_repo/__pycache__/__init__.cpython-312.pyc (deflated 20%)
  adding: iris-feature-store-creation-sqlite/feature_repo/__pycache__/feature_definitions.cpython-312.pyc (deflated 47%)
  adding: iris-feature-store-creation-sqlite/feature_repo/data/ (stored 0%)
  adding: iris-feature-store-creation-sqlite/feature_repo/data/registry.db (deflated 68%)
  adding: iris-feature-store-creation-sqlite/feature_repo/data/iris.parquet (deflated 56%)
  adding: iris-feature-store-creation-sqlite/feature_repo/data/online_store.db (deflated 92%)
  adding: iris-feature-store-creation-sqlite/feature_repo/data/.ipynb_checkpoints/ (stored 0%)
  adding: iris-feature-store-creation-sqlite/feature_repo/.ipynb_checkpoints/ (stored 0%)
  adding: iris-feature-store-creation-sqlite/feature_repo/feature_store.yaml (deflated 44%)
  adding: iris-feature-store-creation-sqlite/.ipynb_checkpoints/ (stored 0%)

In [25]:
from google.colab import files

files.download("iris-feature-store-creation-sqlite.zip")

In [3]:
!unzip iris-feature-store-creation-sqlite.zip

Archive:  iris-feature-store-creation-sqlite.zip
   creating: iris-feature-store-creation-sqlite/
  inflating: iris-feature-store-creation-sqlite/README.md
 extracting: iris-feature-store-creation-sqlite/__init__.py
   creating: iris-feature-store-creation-sqlite/feature_repo/
   creating: iris-feature-store-creation-sqlite/feature_repo/__pycache__/
  inflating: iris-feature-store-creation-sqlite/feature_repo/__pycache__/__init__.cpython-312.pyc
  inflating: iris-feature-store-creation-sqlite/feature_repo/__pycache__/test_workflow.cpython-312.pyc
  inflating: iris-feature-store-creation-sqlite/feature_repo/__pycache__/feature_definitions.cpython-312.pyc
 extracting: iris-feature-store-creation-sqlite/feature_repo/__init__.py
  inflating: iris-feature-store-creation-sqlite/feature_repo/feature_store.yaml
   creating: iris-feature-store-creation-sqlite/feature_repo/data/
   creating: iris-feature-store-creation-sqlite/feature_repo/data/.ipynb_checkpoints/
  inflating: iris-feature-store-creation-sqlite/feature_repo/data/iris.parquet
  inflating: iris-feature-store-creation-sqlite/feature_repo/data/registry.db
  inflating: iris-feature-store-creation-sqlite/feature_repo/data/online_store.db
   creating: iris-feature-store-creation-sqlite/feature_repo/.ipynb_checkpoints/
  inflating: iris-feature-store-creation-sqlite/feature_repo/feature_definitions.py
  inflating: iris-feature-store-creation-sqlite/.gitignore

In [5]:
!pip install "numpy<2" "pandas==2.2.2"

Collecting numpy<2
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 43.2 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
feast 0.64.0 requires numpy<3,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.35.1 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [15]:
import os
import joblib
import feast
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

# -------------------------------------------------------
# Connect to Feast Feature Store
# -------------------------------------------------------

fs = feast.FeatureStore(repo_path="/content/iris-feature-store-creation-sqlite/feature_repo")

# -------------------------------------------------------
# Create Entity DataFrame
# -------------------------------------------------------

entity_df = pd.read_csv("/content/iris_data_adapted_for_feast.csv")

entity_df = entity_df[["iris_id", "event_timestamp"]]
entity_df["event_timestamp"] = pd.to_datetime(entity_df["event_timestamp"], utc=True)

# -------------------------------------------------------
# Retrieve historical features from Feast
# -------------------------------------------------------

training_df = fs.get_historical_features(
    entity_df=entity_df,
    features=[
        "iris_features:sepal_length",
        "iris_features:sepal_width",
        "iris_features:petal_length",
        "iris_features:petal_width",
        "iris_features:sepal_area",
        "iris_features:petal_area",
        "iris_features:sepal_ratio",
        "iris_features:petal_ratio",
        "iris_features:flower_area",
        "iris_features:petal_to_sepal_ratio",
    ],
).to_df()

# -------------------------------------------------------
# Add target labels
# -------------------------------------------------------

labels = pd.read_csv("/content/iris_data_adapted_for_feast.csv")[["iris_id", "species"]]

training_df = training_df.merge(labels, on="iris_id")

# -------------------------------------------------------
# Prepare train/test data
# -------------------------------------------------------

X = training_df.drop(
    columns=[
        "iris_id",
        "event_timestamp",
        "species",
    ]
)

y = training_df["species"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.4,
    stratify=y,
    random_state=42,
)

# -------------------------------------------------------
# Train model
# -------------------------------------------------------

model = DecisionTreeClassifier(
    max_depth=3,
    random_state=1,
)

model.fit(X_train, y_train)

# -------------------------------------------------------
# Evaluate
# -------------------------------------------------------

prediction = model.predict(X_test)

print(
    "Accuracy:",
    metrics.accuracy_score(y_test, prediction),
)

# -------------------------------------------------------
# Save predictions
# -------------------------------------------------------

results = X_test.copy()

results["Actual"] = y_test.values
results["Predicted"] = prediction

artifact_dir = "./artifacts"

os.makedirs(artifact_dir, exist_ok=True)

results.to_csv(
    f"{artifact_dir}/predictions.csv",
    index=False,
)

# -------------------------------------------------------
# Save model
# -------------------------------------------------------

joblib.dump(
    model,
    f"{artifact_dir}/model.joblib",
)

Accuracy: 1.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

['./artifacts/model.joblib']

In [25]:
print(X_train.columns.tolist())

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'sepal_area', 'petal_area', 'sepal_ratio', 'petal_ratio', 'flower_area', 'petal_to_sepal_ratio']

In [3]:
entity_df.head()

   iris_id            event_timestamp
0     1001 2025-09-17 10:40:17.102131
1     1001 2025-09-18 10:40:17.102131
2     1001 2025-09-19 10:40:17.102131
3     1001 2025-09-20 10:40:17.102131
4     1001 2025-09-21 10:40:17.102131

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [6]:
entity_df.dtypes

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

iris_id                          int64
event_timestamp    datetime64[ns, UTC]
dtype: object

In [9]:
df = pd.read_parquet("/content/iris-feature-store-creation-sqlite/feature_repo/data/iris.parquet")

print(df.dtypes)

event_timestamp         datetime64[ns, UTC]
iris_id                               int64
sepal_length                        float64
sepal_width                         float64
petal_length                        float64
petal_width                         float64
species                              object
created_timestamp       datetime64[ns, UTC]
sepal_area                          float64
petal_area                          float64
sepal_ratio                         float64
petal_ratio                         float64
flower_area                         float64
petal_to_sepal_ratio                float64
dtype: object

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [15]:
print(df["event_timestamp"].min())
print(df["event_timestamp"].max())

2025-09-17 10:40:17.102131+00:00
2025-10-01 10:40:17.102131+00:00

In [16]:
!cd /content/iris-feature-store-creation-sqlite/feature_repo/ && feast materialize 2025-09-17T00:00:00 2025-10-02T00:00:00

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/usr/local/lib/python3.12/dist-packages/xarray/core/dtypes.py:111: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  NAT_TYPES = {np.datetime64("NaT").dtype, np.timedelta64("NaT").dtype}
Materializing 1 feature views from 2025-09-17 00:00:00+00:00 to 2025-10-02 00:00:00+00:00 into the sqlite online store.

iris_features:

In [18]:
import pandas as pd

df = pd.read_parquet("/content/iris-feature-store-creation-sqlite/feature_repo/data/iris.parquet")
print(df.shape)
print(df.head())

(45, 14)
                   event_timestamp  iris_id  sepal_length  sepal_width  \
0 2025-09-17 10:40:17.102131+00:00     1001          5.52         2.53
1 2025-09-18 10:40:17.102131+00:00     1001          5.50         2.24
2 2025-09-19 10:40:17.102131+00:00     1001          5.55         2.47
3 2025-09-20 10:40:17.102131+00:00     1001          5.45         2.37
4 2025-09-21 10:40:17.102131+00:00     1001          5.65         2.52

   petal_length  petal_width     species                created_timestamp  \
0          3.86         1.13  versicolor 2025-10-02 10:40:17.172178+00:00
1          3.60         1.08  versicolor 2025-10-02 10:40:17.172178+00:00
2          3.75         1.08  versicolor 2025-10-02 10:40:17.172178+00:00
3          3.92         1.20  versicolor 2025-10-02 10:40:17.172178+00:00
4          3.95         1.17  versicolor 2025-10-02 10:40:17.172178+00:00

   sepal_area  petal_area  sepal_ratio  petal_ratio  flower_area  \
0     13.9656      4.3618     2.181818     3.415929      18.3274
1     12.3200      3.8880     2.455357     3.333333      16.2080
2     13.7085      4.0500     2.246964     3.472222      17.7585
3     12.9165      4.7040     2.299578     3.266667      17.6205
4     14.2380      4.6215     2.242063     3.376068      18.8595

   petal_to_sepal_ratio
0              0.312325
1              0.315584
2              0.295437
3              0.364185
4              0.324589

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [19]:
import feast
import pandas as pd
import joblib


class IrisClassificationModel:

    def __init__(self):
        # Load trained model
        self.model = joblib.load("/content/artifacts/model.joblib")

        # Connect to Feast
        self.fs = feast.FeatureStore(repo_path="/content/iris-feature-store-creation-sqlite/feature_repo")

    def predict(self, iris_ids):

        # Fetch online features from Feast
        feature_vector = self.fs.get_online_features(
            features=[
                "iris_features:sepal_length",
                "iris_features:sepal_width",
                "iris_features:petal_length",
                "iris_features:petal_width",
                "iris_features:sepal_area",
                "iris_features:petal_area",
                "iris_features:sepal_ratio",
                "iris_features:petal_ratio",
                "iris_features:flower_area",
                "iris_features:petal_to_sepal_ratio",
            ],
            entity_rows=[
                {"iris_id": iris_id}
                for iris_id in iris_ids
            ],
        )


        df = pd.DataFrame(feature_vector.to_dict())
        # Keep only feature columns
        feature_order = [
            'sepal_length',
            'sepal_width',
            'petal_length',
            'petal_width',
            'sepal_area',
            'petal_area',
            'sepal_ratio',
            'petal_ratio',
            'flower_area',
            'petal_to_sepal_ratio'
        ]

        X = df[feature_order]
        print(df)

        # Predict species
        df["predicted_species"] = self.model.predict(X)

        return df[["iris_id", "predicted_species"]]

In [11]:
def make_iris_prediction():
    iris_ids = [1001, 1002, 1003]

    model = IrisClassificationModel()

    predictions = model.predict(iris_ids)

    print(predictions)

In [20]:
make_iris_prediction()

   iris_id  sepal_area  petal_ratio  petal_length  sepal_width  sepal_ratio  \
0     1001      12.862     3.522936          3.84         2.36     2.309322
1     1002      14.036     6.450000          1.29         2.90     1.668965
2     1003      16.490     4.103448          1.19         3.40     1.426471

   petal_to_sepal_ratio  petal_area  sepal_length  petal_width  flower_area
0              0.325424      4.1856          5.45         1.09      17.0476
1              0.018381      0.2580          4.84         0.20      14.2940
2              0.020928      0.3451          4.85         0.29      16.8351
   iris_id predicted_species
0     1001        versicolor
1     1002            setosa
2     1003            setosa

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [6]:
!pwd

/content

In [9]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("/content/iris-feature-store-creation-sqlite/feature_repo/data/online_store.db")

cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

print(cursor.fetchall())

df = pd.read_sql(
    "SELECT * FROM iris_feature_store_creation_sqlite_iris_features",
    conn,
)

print(df)

conn.close()

[('iris_feature_store_creation_sqlite_iris_features',)]
                                           entity_key          feature_name  \
0   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...          sepal_length
1   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           sepal_width
2   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...          petal_length
3   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           petal_width
4   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...            sepal_area
5   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...            petal_area
6   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           sepal_ratio
7   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           petal_ratio
8   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           flower_area
9   b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...  petal_to_sepal_ratio
10  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...          sepal_length
11  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           sepal_width
12  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...          petal_length
13  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           petal_width
14  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...            sepal_area
15  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...            petal_area
16  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           sepal_ratio
17  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           petal_ratio
18  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           flower_area
19  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...  petal_to_sepal_ratio
20  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...          sepal_length
21  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           sepal_width
22  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...          petal_length
23  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           petal_width
24  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...            sepal_area
25  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...            petal_area
26  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           sepal_ratio
27  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           petal_ratio
28  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...           flower_area
29  b'\x01\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00...  petal_to_sepal_ratio

                value vector_value    event_ts  created_ts
0         b'5ff\xae@'         None  1759315217  1759401617
1        b'5=\n\x17@'         None  1759315217  1759401617
2      b'5\x8f\xc2u@'         None  1759315217  1759401617
3   b'5\x1f\x85\x8b?'         None  1759315217  1759401617
4      b'5\xc1\xcaMA'         None  1759315217  1759401617
5      b'5o\xf0\x85@'         None  1759315217  1759401617
6   b'5\xef\xcb\x13@'         None  1759315217  1759401617
7         b'5\xc8wa@'         None  1759315217  1759401617
8         b'5|a\x88A'         None  1759315217  1759401617
9   b'5\xf0\x9d\xa6>'         None  1759315217  1759401617
10     b'5H\xe1\x9a@'         None  1759315217  1759401617
11     b'5\x9a\x999@'         None  1759315217  1759401617
12  b'5\xb8\x1e\xa5?'         None  1759315217  1759401617
13     b'5\xcd\xccL>'         None  1759315217  1759401617
14        b'5u\x93`A'         None  1759315217  1759401617
15  b'5\x93\x18\x84>'         None  1759315217  1759401617
16  b'5\xa9\xa0\xd5?'         None  1759315217  1759401617
17        b'5ff\xce@'         None  1759315217  1759401617
18        b'59\xb4dA'         None  1759315217  1759401617
19     b'5d\x94\x96<'         None  1759315217  1759401617
20        b'533\x9b@'         None  1759315217  1759401617
21     b'5\x9a\x99Y@'         None  1759315217  1759401617
22     b'5\xecQ\x98?'         None  1759315217  1759401617
23     b'5\xe1z\x94>'         None  1759315217  1759401617
24  b'5\x85\xeb\x83A'         None  1759315217  1759401617
25  b'5\xf2\xb0\xb0>'         None  1759315217  1759401617
26  b'5\x97\x96\xb6?'         None  1759315217  1759401617
27        b'5sO\x83@'         None  1759315217  1759401617
28     b'5I\xae\x86A'         None  1759315217  1759401617
29     b'5\xdap\xab<'         None  1759315217  1759401617

In [21]:
! feast init iris-feature-store-creation-bigquery

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'

Creating a new Feast repository in /content/iris-feature-store-creation-bigquery.